#!/bin/bash

#SBATCH --cpus-per-task=20
#SBATCH --job-name=TSIT_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=2
#SBATCH --qos=gpu_free
#SBATCH --mem=350GB
#SBATCH --time=12:00:00
#SBATCH --chdir /scratch/izar/xugao/testLogs
#SBATCH --output=/scratch/izar/xugao/testLogs/TSIT/test_nvae_%j.out
#SBATCH --error=/scratch/izar/xugao/testLogs/TSIT/test_nvae_%j.err

module load gcc cuda
echo "hello from 'hostname'"

source /home/xugao/venvs/venv-for-demo/bin/activate
cd /home/xugao/gitRepo/TSIT
python test.py \
--name 'train_vae_1' \
--use_vae \
--display_env 'no_vae_cl_1' \
--task 'AST' \
--gpu_ids 0 \
--batchSize 1 \
--dataset_mode 'night2day' \
--croot '/home/xugao/gitRepo/swapping-autoencoder-pytorch/datasets/testsets' \
--sroot '/home/xugao/gitRepo/swapping-autoencoder-pytorch/datasets/nightVisionDatasets' \
--nThreads 4 \
--no_pairing_check \
--no_instance \
--alpha 1.0 \
--dayJson "/home/xugao/gitRepo/swapping-autoencoder-pytorch/datasets/nightVisionDatasets/clean_day_images.json" \
--which_epoch 'latest'

echo "bye from 'hostname'"